name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Display Build Message
        run: echo "Build Success!"

      - name: Verify HTML File
        run: test -f index.html

      - name: Notify Slack
        if: success()
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{"text":"🟢 CI Pipeline completed successfully for devops-webapp!"}' \
            "${{ secrets.SLACK_WEBHOOK_URL }}"